### ISSUE TITLE
use env variable for git auth

### ISSUE THREAD

**Issue by tracker1** [finom/deploy-to-git#1]
You don't want your git token checked into your code... this will allow others to publish to your project.

You should allow for a `DEPLOYTOGIT_REPOSITORY` environment variable, that way it can be encrypted in yoru travis.yml, or outside your codebase.

**Comment by finom** [comment]
@tracker1 but the code still can get DEPLOYTOGIT_REPOSITORY, I cannot see the difference between GH_TOKEN@... and DEPLOYTOGIT_REPOSITORY.

**Comment by finom** [comment]
The proposition is not clear for me, I am going to close the issue soon.
