### ISSUE TITLE
Syntax problem

### ISSUE THREAD

**Issue by ghost** [finom/deploy-to-git#3]
Hello,

I'm trying to use your module on 
npm 3.10.10  
visual studio code : powershell terminal 
Windows 10

I have use the script normally, it clone and build perfectly. 
But it doesn't execute any "execSync" starting with blank line.

The only way for me to make it work perfectly is to put everything on the same line.

Exemple if I want "push" to work I must change : 

```
execSync(`
    cd ${config.folder} &&
    git push --tags ${config.repository} ${config.branch}
`, { cwd });
```
to :

`execSync('cd ${config.folder} && git push --tags ${config.repository} ${config.branch}', { cwd });`

anyway, thanks you for you job ;)

**Comment by tiagosomda** [comment]
ha! same problem here.
I fixed it just like you mentioned, but the pull request continuous integration seems to be failing due to some syntax req: https://github.com/finom/deploy-to-git/pull/4

**Comment by finom** [comment]
@Ixoh @tiagosomda let me know if you still get the problem.
